theme = "jellybeans"

[editor]
line-number = "relative"
color-modes = true
true-color = true
scrolloff = 10
idle-timeout = 1000
mouse = false
middle-click-paste = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
display-inlay-hints = false
auto-signature-help = false

[keys.normal]
"esc" = [ "collapse_selection", "keep_primary_selection" ]
"{" = [ "goto_prev_paragraph" ]
"}" = [ "goto_next_paragraph" ]

[keys.select]
"{" = [ "goto_prev_paragraph" ]
"}" = [ "goto_next_paragraph" ]
