# https://github.com/helix-editor/helix/blob/master/runtime/themes/jellybeans.toml
# Located in ~/.congfig/helix/runtime/themes/fattybeans.toml
#     inherits = "jellybeans"
#     "ui.background" ={}
theme = "fattybeans"

[editor]
line-number = "relative"
color-modes = true
true-color = true
mouse = false
middle-click-paste = true
rulers = [80, 120]
idle-timeout = 1000

[editor.lsp]
display-messages = true
auto-signature-help = false

[keys.normal]
"esc" = [ "collapse_selection", "keep_primary_selection" ]
"D" = [ "ensure_selections_forward", "extend_to_line_end", "delete_selection" ]
"C-left" = [ "goto_previous_buffer" ]
"C-right" = [ "goto_next_buffer" ]
"C-up" = [ "page_cursor_half_up" ]
"C-down" = [ "page_cursor_half_down" ]
"C-b" = [ ":sh make" ]
